-- ============================================================================
-- Supabase Setup Script for The Kala Lawyers Website
-- Copy and run these commands in the SQL Editor on your Supabase Dashboard.
-- ============================================================================

-- 1. Create the 'enquiries' table (Contact Form Leads)
CREATE TABLE IF NOT EXISTS public.enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT DEFAULT 'N/A',
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    referred_by TEXT DEFAULT 'Direct',
    practice_area TEXT DEFAULT 'General Inquiry',
    message TEXT NOT NULL,
    status TEXT DEFAULT 'New',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on enquiries table
ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public (anonymous) to submit contact form (Insert)
DROP POLICY IF EXISTS "Allow public submissions" ON public.enquiries;
CREATE POLICY "Allow public submissions" 
ON public.enquiries 
FOR INSERT 
WITH CHECK (true);

-- Policy: Allow only authenticated admins to view/delete enquiries (Select, Delete)
DROP POLICY IF EXISTS "Allow admin read access" ON public.enquiries;
CREATE POLICY "Allow admin read access" 
ON public.enquiries 
FOR SELECT 
TO authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow admin update access" ON public.enquiries;
CREATE POLICY "Allow admin update access" 
ON public.enquiries 
FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admin delete access" ON public.enquiries;
CREATE POLICY "Allow admin delete access" 
ON public.enquiries 
FOR DELETE 
TO authenticated 
USING (true);


-- 2. Create the 'case_wins' table (Court Victories)
CREATE TABLE IF NOT EXISTS public.case_wins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    pdf_filename TEXT,
    category TEXT DEFAULT 'General',
    date_added TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on case_wins table
ALTER TABLE public.case_wins ENABLE ROW LEVEL SECURITY;

-- Policy: Allow everyone (anonymous + authenticated) to read case victories (Select)
DROP POLICY IF EXISTS "Allow public read case victories" ON public.case_wins;
CREATE POLICY "Allow public read case victories" 
ON public.case_wins 
FOR SELECT 
USING (true);

-- Policy: Allow only authenticated admins to create/update/delete case victories (Insert, Update, Delete)
DROP POLICY IF EXISTS "Allow admin write case victories" ON public.case_wins;
DROP POLICY IF EXISTS "Allow admin update case victories" ON public.case_wins;
DROP POLICY IF EXISTS "Allow admin delete case victories" ON public.case_wins;
CREATE POLICY "Allow admin read/write case victories" 
ON public.case_wins 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);


-- 3. Create the 'practice_areas' table
CREATE TABLE IF NOT EXISTS public.practice_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    icon TEXT,
    short_description TEXT NOT NULL,
    long_description TEXT NOT NULL,
    specialties JSONB NOT NULL DEFAULT '[]'::jsonb, -- array of strings
    statutes JSONB NOT NULL DEFAULT '[]'::jsonb,    -- array of strings
    faqs JSONB NOT NULL DEFAULT '[]'::jsonb         -- array of objects
);

-- Enable Row Level Security (RLS) on practice_areas table
ALTER TABLE public.practice_areas ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read of practice areas (Select)
DROP POLICY IF EXISTS "Allow public read practice areas" ON public.practice_areas;
CREATE POLICY "Allow public read practice areas" 
ON public.practice_areas 
FOR SELECT 
USING (true);

-- Policy: Allow only authenticated admins to manage practice areas (Insert, Update, Delete)
DROP POLICY IF EXISTS "Allow admin update practice areas" ON public.practice_areas;
DROP POLICY IF EXISTS "Allow admin read/write practice areas" ON public.practice_areas;
CREATE POLICY "Allow admin read/write practice areas" 
ON public.practice_areas 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);


-- 4. Create the 'diary_records' table (Admin Case Diary + Calendar)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.diary_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL,
    court_name TEXT NOT NULL,
    previous_case_date DATE NULL,


-- 4. Create the 'diary_records' table (Admin Case Diary + Calendar)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS public.diary_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL,
    court_name TEXT NOT NULL,
    previous_case_date DATE NULL,
    case_number TEXT NOT NULL,
    case_title TEXT NOT NULL,
    stage TEXT NOT NULL DEFAULT 'Listed',
    client_name TEXT NULL,
    advocates TEXT NULL,
    judge_name TEXT NULL,
    hearing_mode TEXT NULL,
    recurrence TEXT NULL,
    notes TEXT NULL,
    stage_history JSONB NOT NULL DEFAULT '[]'::jsonb,
    next_date DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT check_diary_dates CHECK (previous_case_date IS NULL OR previous_case_date < date),
    CONSTRAINT check_diary_next_date CHECK (next_date IS NULL OR next_date > date),
    CONSTRAINT check_diary_stage_history_array CHECK (jsonb_typeof(stage_history) = 'array')
);

ALTER TABLE public.diary_records
    ADD COLUMN IF NOT EXISTS client_name TEXT NULL,
    ADD COLUMN IF NOT EXISTS advocates TEXT NULL,
    ADD COLUMN IF NOT EXISTS judge_name TEXT NULL,
    ADD COLUMN IF NOT EXISTS hearing_mode TEXT NULL,
    ADD COLUMN IF NOT EXISTS recurrence TEXT NULL,
    ADD COLUMN IF NOT EXISTS notes TEXT NULL;

DROP INDEX IF EXISTS uq_diary_records_case_date;

CREATE INDEX IF NOT EXISTS idx_diary_records_case_date_lookup 
ON public.diary_records (lower(court_name), lower(case_number), date);

CREATE INDEX IF NOT EXISTS idx_diary_records_date 
ON public.diary_records (date DESC);

ALTER TABLE public.diary_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated diary read" ON public.diary_records;
CREATE POLICY "Allow authenticated diary read"
ON public.diary_records
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow authenticated diary insert" ON public.diary_records;
CREATE POLICY "Allow authenticated diary insert"
ON public.diary_records
FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated diary update" ON public.diary_records;
CREATE POLICY "Allow authenticated diary update"
ON public.diary_records
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated diary delete" ON public.diary_records;
CREATE POLICY "Allow authenticated diary delete"
ON public.diary_records
FOR DELETE
TO authenticated
USING (true);

CREATE OR REPLACE FUNCTION public.touch_diary_record_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_touch_diary_record_updated_at ON public.diary_records;
CREATE TRIGGER trigger_touch_diary_record_updated_at
BEFORE UPDATE ON public.diary_records
FOR EACH ROW
EXECUTE FUNCTION public.touch_diary_record_updated_at();

CREATE OR REPLACE FUNCTION public.prefill_next_diary_record()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.next_date IS NOT NULL THEN
            DELETE FROM public.diary_records 
            WHERE lower(case_number) = lower(OLD.case_number) 
              AND lower(court_name) = lower(OLD.court_name)
              AND date = OLD.next_date
              AND previous_case_date = OLD.date
              AND stage_history = '[]'::jsonb
              AND next_date IS NULL;
        END IF;
        RETURN OLD;
    END IF;

    IF (TG_OP = 'INSERT' AND NEW.next_date IS NOT NULL) OR 
       (TG_OP = 'UPDATE' AND NEW.next_date IS NOT NULL AND (OLD.next_date IS NULL OR NEW.next_date <> OLD.next_date)) THEN
        INSERT INTO public.diary_records (
            date,
            court_name,
            previous_case_date,
            case_number,
            case_title,
            stage,
            client_name,
            advocates,
            judge_name,
            hearing_mode,
            recurrence,
            notes,
            stage_history,
            next_date
        ) VALUES (
            NEW.next_date,
            NEW.court_name,
            NEW.date,
            NEW.case_number,
            NEW.case_title,
            NEW.stage,
            NEW.client_name,
            NEW.advocates,
            NEW.judge_name,
            NEW.hearing_mode,
            NEW.recurrence,
            NEW.notes,
            '[]'::jsonb,
            NULL
        )
        ON CONFLICT DO NOTHING;
    END IF;

    IF (TG_OP = 'UPDATE' AND OLD.next_date IS NOT NULL AND (NEW.next_date IS NULL OR NEW.next_date <> OLD.next_date)) THEN
        DELETE FROM public.diary_records 
        WHERE lower(case_number) = lower(OLD.case_number) 
          AND lower(court_name) = lower(OLD.court_name)
          AND date = OLD.next_date
          AND previous_case_date = OLD.date
          AND stage_history = '[]'::jsonb
          AND next_date IS NULL;
    END IF;

    IF (TG_OP = 'UPDATE' AND (NEW.case_title <> OLD.case_title OR NEW.case_number <> OLD.case_number OR NEW.court_name <> OLD.court_name OR NEW.date <> OLD.date OR NEW.client_name IS DISTINCT FROM OLD.client_name OR NEW.advocates IS DISTINCT FROM OLD.advocates OR NEW.judge_name IS DISTINCT FROM OLD.judge_name OR NEW.hearing_mode IS DISTINCT FROM OLD.hearing_mode OR NEW.recurrence IS DISTINCT FROM OLD.recurrence OR NEW.notes IS DISTINCT FROM OLD.notes)) THEN
        UPDATE public.diary_records
        SET case_title = NEW.case_title,
            case_number = NEW.case_number,
            court_name = NEW.court_name,
            previous_case_date = NEW.date,
            client_name = NEW.client_name,
            advocates = NEW.advocates,
            judge_name = NEW.judge_name,
            hearing_mode = NEW.hearing_mode,
            recurrence = NEW.recurrence,
            notes = NEW.notes
        WHERE lower(case_number) = lower(OLD.case_number)
          AND lower(court_name) = lower(OLD.court_name)
          AND previous_case_date = OLD.date
          AND stage_history = '[]'::jsonb;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_prefill_next_diary_record ON public.diary_records;
CREATE TRIGGER trigger_prefill_next_diary_record
AFTER INSERT OR UPDATE OR DELETE ON public.diary_records
FOR EACH ROW
EXECUTE FUNCTION public.prefill_next_diary_record();


-- ============================================================================
-- 5. Storage Bucket Setup
-- ============================================================================
-- Note: Create a public storage bucket named 'case-judgments' in the Storage tab of your dashboard.
-- Once created, you can execute the following policies (or set them via the UI):

-- Policy: Allow public read of files inside the 'case-judgments' bucket
-- (Navigate to Storage -> Policies -> 'case-judgments' bucket -> Add policy -> "Allow public read access")

-- Policy: Allow authenticated users (admins) to upload/update/delete files
-- (Navigate to Storage -> Policies -> 'case-judgments' bucket -> Add policy -> "Allow authenticated write access")
