-- ============================================================================
-- Supabase Setup Script for The Kala Lawyers Website
-- Copy and run these commands in the SQL Editor on your Supabase Dashboard.
-- ============================================================================

-- 1. Create the 'enquiries' table (Contact Form Leads)
CREATE TABLE IF NOT EXISTS public.enquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT DEFAULT 'N/A',
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    referred_by TEXT DEFAULT 'Direct',
    practice_area TEXT DEFAULT 'General Inquiry',
    message TEXT NOT NULL,
    status TEXT DEFAULT 'New',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on enquiries table
ALTER TABLE public.enquiries ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public (anonymous) to submit contact form (Insert)
CREATE POLICY "Allow public submissions" 
ON public.enquiries 
FOR INSERT 
WITH CHECK (true);

-- Policy: Allow only authenticated admins to view/delete enquiries (Select, Delete)
CREATE POLICY "Allow admin read access" 
ON public.enquiries 
FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Allow admin delete access" 
ON public.enquiries 
FOR DELETE 
TO authenticated 
USING (true);


-- 2. Create the 'case_wins' table (Court Victories)
CREATE TABLE IF NOT EXISTS public.case_wins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    pdf_filename TEXT,
    category TEXT DEFAULT 'General',
    date_added TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on case_wins table
ALTER TABLE public.case_wins ENABLE ROW LEVEL SECURITY;

-- Policy: Allow everyone (anonymous + authenticated) to read case victories (Select)
CREATE POLICY "Allow public read case victories" 
ON public.case_wins 
FOR SELECT 
USING (true);

-- Policy: Allow only authenticated admins to create/update/delete case victories (Insert, Update, Delete)
CREATE POLICY "Allow admin write case victories" 
ON public.case_wins 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Allow admin update case victories" 
ON public.case_wins 
FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Allow admin delete case victories" 
ON public.case_wins 
FOR DELETE 
TO authenticated 
USING (true);


-- 3. Create the 'practice_areas' table
CREATE TABLE IF NOT EXISTS public.practice_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    icon TEXT,
    short_description TEXT NOT NULL,
    long_description TEXT NOT NULL,
    specialties JSONB NOT NULL DEFAULT '[]'::jsonb, -- array of strings
    statutes JSONB NOT NULL DEFAULT '[]'::jsonb,    -- array of strings
    faqs JSONB NOT NULL DEFAULT '[]'::jsonb         -- array of objects
);

-- Enable Row Level Security (RLS) on practice_areas table
ALTER TABLE public.practice_areas ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read of practice areas (Select)
CREATE POLICY "Allow public read practice areas" 
ON public.practice_areas 
FOR SELECT 
USING (true);

-- Policy: Allow only authenticated admins to modify practice areas (Update)
CREATE POLICY "Allow admin update practice areas" 
ON public.practice_areas 
FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);


-- ============================================================================
-- 4. Storage Bucket Setup
-- ============================================================================
-- Note: Create a public storage bucket named 'case-judgments' in the Storage tab of your dashboard.
-- Once created, you can execute the following policies (or set them via the UI):

-- Policy: Allow public read of files inside the 'case-judgments' bucket
-- (Navigate to Storage -> Policies -> 'case-judgments' bucket -> Add policy -> "Allow public read access")

-- Policy: Allow authenticated users (admins) to upload/update/delete files
-- (Navigate to Storage -> Policies -> 'case-judgments' bucket -> Add policy -> "Allow authenticated write access")
