-- 1. Enable pgcrypto extension if not already enabled (for UUID generation)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 2. Ensure 'practice_areas' Table Exists
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.practice_areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    icon TEXT,
    short_description TEXT NOT NULL,
    long_description TEXT NOT NULL,
    specialties JSONB NOT NULL DEFAULT '[]'::jsonb,
    statutes JSONB NOT NULL DEFAULT '[]'::jsonb,
    faqs JSONB NOT NULL DEFAULT '[]'::jsonb
);

ALTER TABLE public.practice_areas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read practice areas" ON public.practice_areas;
CREATE POLICY "Allow public read practice areas"
ON public.practice_areas
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow admin update practice areas" ON public.practice_areas;
DROP POLICY IF EXISTS "Allow admin read/write practice areas" ON public.practice_areas;
CREATE POLICY "Allow admin read/write practice areas"
ON public.practice_areas
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- ============================================================================
-- 5. Create 'diary_records' Table
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.diary_records (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL,
    court_name TEXT NOT NULL,
    previous_case_date DATE NULL,
    case_number TEXT NOT NULL,
    case_title TEXT NOT NULL,
    stage TEXT NOT NULL,
    client_name TEXT NULL,
    advocates TEXT NULL,
    judge_name TEXT NULL,
    hearing_mode TEXT NULL,
    recurrence TEXT NULL,
    notes TEXT NULL,
    stage_history JSONB NOT NULL DEFAULT '[]'::jsonb,
    next_date DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT check_diary_dates CHECK (previous_case_date IS NULL OR previous_case_date < date),
    CONSTRAINT check_diary_next_date CHECK (next_date IS NULL OR next_date > date),
    CONSTRAINT check_diary_stage_history_array CHECK (jsonb_typeof(stage_history) = 'array')
);

ALTER TABLE public.diary_records
    ADD COLUMN IF NOT EXISTS client_name TEXT NULL,
    ADD COLUMN IF NOT EXISTS advocates TEXT NULL,
    ADD COLUMN IF NOT EXISTS judge_name TEXT NULL,
    ADD COLUMN IF NOT EXISTS hearing_mode TEXT NULL,
    ADD COLUMN IF NOT EXISTS recurrence TEXT NULL,
    ADD COLUMN IF NOT EXISTS notes TEXT NULL;

ALTER TABLE public.diary_records
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

DROP INDEX IF EXISTS uq_diary_records_case_date;

CREATE INDEX IF NOT EXISTS idx_diary_records_case_date_lookup 
ON public.diary_records (lower(court_name), lower(case_number), date);

-- Enable Row Level Security (RLS)
ALTER TABLE public.diary_records ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated admin sessions to perform CRUD.
DROP POLICY IF EXISTS "Allow admin read/write diary_records" ON public.diary_records;
CREATE POLICY "Allow admin read/write diary_records"
ON public.diary_records
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Indexes for diary query optimization
CREATE INDEX IF NOT EXISTS idx_diary_records_date 
ON public.diary_records (date DESC);

-- Case-insensitive b-tree indexes for searching case titles, numbers, and courts
CREATE INDEX IF NOT EXISTS idx_diary_records_case_title_lower 
ON public.diary_records (lower(case_title));

CREATE INDEX IF NOT EXISTS idx_diary_records_case_number_lower 
ON public.diary_records (lower(case_number));

CREATE INDEX IF NOT EXISTS idx_diary_records_court_name_lower 
ON public.diary_records (lower(court_name));


-- ============================================================================
-- 5. Prefill Automation & Integrity Trigger for 'diary_records'
-- ============================================================================
CREATE OR REPLACE FUNCTION public.prefill_next_diary_record()
RETURNS TRIGGER AS $$
BEGIN
    -- DELETE: clean up generated future draft, then stop before referencing NEW.
    IF TG_OP = 'DELETE' THEN
        IF OLD.next_date IS NOT NULL THEN
            DELETE FROM public.diary_records 
            WHERE lower(case_number) = lower(OLD.case_number) 
              AND lower(court_name) = lower(OLD.court_name)
              AND date = OLD.next_date
              AND previous_case_date = OLD.date
              AND stage_history = '[]'::jsonb
              AND next_date IS NULL;
        END IF;
        RETURN OLD;
    END IF;

    -- A. HANDLE INSERT OR UPDATE of next_date (Prefilling future records)
    IF (TG_OP = 'INSERT' AND NEW.next_date IS NOT NULL) OR 
       (TG_OP = 'UPDATE' AND NEW.next_date IS NOT NULL AND (OLD.next_date IS NULL OR NEW.next_date <> OLD.next_date)) THEN
        
        -- Prevent duplicate prefilled records on the same target date (case-insensitive lookup)
        IF NOT EXISTS (
            SELECT 1 
            FROM public.diary_records 
            WHERE lower(case_number) = lower(NEW.case_number) 
              AND lower(court_name) = lower(NEW.court_name)
              AND date = NEW.next_date
        ) THEN
            INSERT INTO public.diary_records (
                date,
                court_name,
                previous_case_date,
            case_number,
            case_title,
            stage,
            client_name,
            advocates,
            judge_name,
            hearing_mode,
            recurrence,
            notes,
            stage_history,
            next_date
        ) VALUES (
            NEW.next_date,
            NEW.court_name,
            NEW.date,
            NEW.case_number,
            NEW.case_title,
            NEW.stage,
            NEW.client_name,
            NEW.advocates,
            NEW.judge_name,
            NEW.hearing_mode,
            NEW.recurrence,
            NEW.notes,
            '[]'::jsonb,
            NULL
        );
        END IF;
    END IF;

    -- B. HANDLE UPDATE OF next_date (Clean up old orphaned prefilled drafts)
    IF (TG_OP = 'UPDATE' AND OLD.next_date IS NOT NULL AND (NEW.next_date IS NULL OR NEW.next_date <> OLD.next_date)) THEN
        DELETE FROM public.diary_records 
        WHERE lower(case_number) = lower(OLD.case_number) 
          AND lower(court_name) = lower(OLD.court_name)
          AND date = OLD.next_date
          AND previous_case_date = OLD.date
          AND stage_history = '[]'::jsonb;
    END IF;

    -- C. HANDLE UPDATE OF case metadata OR parent date (Cascade changes to future prefilled drafts to prevent data drift and broken chains)
    IF (TG_OP = 'UPDATE' AND (NEW.case_title <> OLD.case_title OR NEW.case_number <> OLD.case_number OR NEW.court_name <> OLD.court_name OR NEW.date <> OLD.date)) THEN
        UPDATE public.diary_records 
        SET case_title = NEW.case_title,
            case_number = NEW.case_number,
            court_name = NEW.court_name,
            previous_case_date = NEW.date,
            client_name = NEW.client_name,
            advocates = NEW.advocates,
            judge_name = NEW.judge_name,
            hearing_mode = NEW.hearing_mode,
            recurrence = NEW.recurrence,
            notes = NEW.notes
        WHERE lower(case_number) = lower(OLD.case_number) 
          AND lower(court_name) = lower(OLD.court_name)
          AND previous_case_date = OLD.date
          AND stage_history = '[]'::jsonb;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.touch_diary_record_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_touch_diary_record_updated_at ON public.diary_records;
CREATE TRIGGER trigger_touch_diary_record_updated_at
BEFORE UPDATE ON public.diary_records
FOR EACH ROW
EXECUTE FUNCTION public.touch_diary_record_updated_at();

CREATE OR REPLACE TRIGGER trigger_prefill_next_diary_record
AFTER INSERT OR UPDATE OR DELETE ON public.diary_records
FOR EACH ROW
EXECUTE FUNCTION public.prefill_next_diary_record();







    description TEXT NOT NULL,
    pdf_filename TEXT NOT NULL,
    category TEXT NOT NULL,
    date_added TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.case_wins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read case victories" ON public.case_wins;
CREATE POLICY "Allow public read case victories"
ON public.case_wins
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow admin read/write case victories" ON public.case_wins;
CREATE POLICY "Allow admin read/write case victories"
ON public.case_wins
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);